// Code generated by encore. DO NOT EDIT.

package employees

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// CreateEmployee creates a new employee.
	CreateEmployee(ctx context.Context, p *CreateEmployeeRequest) (*GetEmployeeResponse, error)

	// ListEmployees returns all active employees, with an optional search filter.
	// SA sees all; ADM is scoped to their client; HR is scoped to their DZO.
	ListEmployees(ctx context.Context, p *ListEmployeesParams) (*ListEmployeesResponse, error)

	// GetEmployee returns a single employee by ID.
	// ADM is scoped to their client; HR is scoped to their DZO.
	GetEmployee(ctx context.Context, id string) (*GetEmployeeResponse, error)

	// PatchEmployee partially updates an employee. ADM is scoped to their client.
	PatchEmployee(ctx context.Context, id string, p *UpdateEmployeeRequest) (*GetEmployeeResponse, error)

	// GetMyEmployee returns the employee record for the currently authenticated user.
	GetMyEmployee(ctx context.Context) (*GetEmployeeResponse, error)

	// DeleteEmployee soft-deletes an employee by setting is_deleted=true.
	// ADM is scoped to their client.
	DeleteEmployee(ctx context.Context, id string) (*DeleteEmployeeResponse, error)

	BulkDeleteEmployees(ctx context.Context, p *BulkDeleteRequest) (*BulkDeleteResponse, error)

	// UploadEmployees validates uploaded employees .xlsx file before import.
	UploadEmployees(ctx context.Context, p *UploadEmployeesRequest) (*UploadResponse, error)

	// ImportEmployees imports employees from uploaded .xlsx file.
	ImportEmployees(ctx context.Context, p *ImportEmployeesRequest) (*ImportResponse, error)
}
