// Code generated by encore. DO NOT EDIT.

package contractssuppliers

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// CreateContract creates a new supplier contract.
	CreateContract(ctx context.Context, supplierID string, p *CreateContractRequest) (*GetContractResponse, error)

	// ListContracts returns a paginated, filtered list of supplier contracts.
	ListContracts(ctx context.Context, p *ListContractsFilter) (*ListContractsResponse, error)

	// GetContract returns a single supplier contract by ID.
	GetContract(ctx context.Context, id string) (*GetContractResponse, error)

	// UpdateContract patches a supplier contract.
	UpdateContract(ctx context.Context, id string, p *UpdateContractRequest) (*GetContractResponse, error)

	// DeleteContract soft-deletes a supplier contract (sets is_active=false).
	DeleteContract(ctx context.Context, id string) (*DeleteContractResponse, error)

	// AddAmendment records an amendment (доп. соглашение) on the contract.
	// Only one amendment is allowed per contract; a second attempt returns 409.
	// Recomputes total_with_amendment and remaining_amount.
	AddAmendment(ctx context.Context, id string, p *AmendmentRequest) (*GetContractResponse, error)

	// UploadFile attaches a contract document (pdf/jpg/png) to the contract.
	// Replaces any previously uploaded file. Max size 25 MB.
	UploadFile(ctx context.Context, id string, p *UploadFileRequest) (*GetContractResponse, error)

	// GetFileURL returns a short-lived signed URL to download the contract's file.
	GetFileURL(ctx context.Context, id string) (*FileURLResponse, error)

	// ImportContracts bulk-imports contracts from CSV/XLSX.
	ImportContracts(ctx context.Context) (*ImportResponse, error)
}
