// Code generated by encore. DO NOT EDIT.

package requests

import (
	"context"
	uuid "encore.dev/types/uuid"
)

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// CreateAdminRequest creates a main request for external learning.
	CreateAdminRequest(ctx context.Context, p *CreateAdminRequestRequest) (*GetRequestResponse, error)

	// ListRequests returns main requests visible to admins.
	ListRequests(ctx context.Context) (*ListRequestsResponse, error)

	// GetRequest returns request details for admins.
	GetRequest(ctx context.Context, id uuid.UUID) (*GetRequestResponse, error)

	// SubmitRequest splits a main request into HR subrequests.
	SubmitRequest(ctx context.Context, id uuid.UUID) (*GetRequestResponse, error)

	// PrepareAdminRequest fills training, supplier-contract and budget data before admin final approval.
	PrepareAdminRequest(ctx context.Context, id uuid.UUID, p *PrepareAdminRequestRequest) (*GetRequestResponse, error)

	// RemoveAdminRequestEmployee removes employee from main request during admin preparation.
	RemoveAdminRequestEmployee(ctx context.Context, id uuid.UUID, p *RemoveRequestEmployeeRequest) (*GetRequestResponse, error)

	// RecreateRejectedRequest creates a new version of a rejected request.
	RecreateRejectedRequest(ctx context.Context, id uuid.UUID, p *CreateAdminRequestRequest) (*GetRequestResponse, error)

	// CancelAdminRequest cancels a main request and refunds budget if it was written off.
	CancelAdminRequest(ctx context.Context, id uuid.UUID) (*GetRequestResponse, error)

	// ListHRRequests returns subrequests assigned to the current HR.
	ListHRRequests(ctx context.Context) (*ListRequestsResponse, error)

	// GetHRRequest returns HR request details.
	GetHRRequest(ctx context.Context, id uuid.UUID) (*GetRequestResponse, error)

	// UpdateHRRequestEmployees replaces the employee set in an HR subrequest.
	UpdateHRRequestEmployees(ctx context.Context, id uuid.UUID, p *UpdateHRRequestEmployeesRequest) (*GetRequestResponse, error)

	// ApproveHRRequest approves an HR subrequest.
	ApproveHRRequest(ctx context.Context, id uuid.UUID) (*GetRequestResponse, error)

	// CancelHRRequest rejects an HR subrequest.
	CancelHRRequest(ctx context.Context, id uuid.UUID) (*GetRequestResponse, error)

	// CreateHRRequest creates a main request from HR to Admin.
	CreateHRRequest(ctx context.Context, p *CreateHRRequestRequest) (*GetRequestResponse, error)

	// FinalizeAdminRequest finalizes a main request and writes off budget.
	FinalizeAdminRequest(ctx context.Context, id uuid.UUID) (*GetRequestResponse, error)

	// ContinueAdminRequestWithInactiveEmployees confirms inactive employees warning.
	ContinueAdminRequestWithInactiveEmployees(ctx context.Context, id uuid.UUID, p *PrepareAdminRequestRequest) (*GetRequestResponse, error)

	// SaveAdminRequestDraft moves main request back to draft during admin preparation.
	SaveAdminRequestDraft(ctx context.Context, id uuid.UUID) (*GetRequestResponse, error)

	// budget
	GetRequestBudgetHistory(ctx context.Context, id uuid.UUID) (*GetRequestBudgetHistoryResponse, error)

	// CreateArchiveRequest creates a closed/archive request that is immediately completed.
	CreateArchiveRequest(ctx context.Context, p *CreateArchiveRequestRequest) (*GetRequestResponse, error)
}
