// Code generated by encore. DO NOT EDIT.

package organizations

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// CreateOrg creates a new organization. SA only.
	CreateOrg(ctx context.Context, p *CreateOrgRequest) (*GetOrgResponse, error)

	// ListOrgs returns all active organizations. SA and ADM only.
	ListOrgs(ctx context.Context) (*ListOrgsResponse, error)

	// GetOrg returns a single organization by ID. SA and ADM only.
	GetOrg(ctx context.Context, id string) (*GetOrgResponse, error)

	// UpdateOrg partially updates an organization. SA only.
	UpdateOrg(ctx context.Context, id string, p *UpdateOrgRequest) (*GetOrgResponse, error)

	// DeleteOrg soft-deletes an organization by setting is_active=false. SA only.
	DeleteOrg(ctx context.Context, id string) (*DeleteOrgResponse, error)
}
