// Code generated by encore. DO NOT EDIT.

package dzo

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// CreateDZO creates a new DZO.
	CreateDZO(ctx context.Context, p *CreateDZORequest) (*GetDZOResponse, error)

	// ListDZO returns all active DZO. SA sees all; ADM sees only their client's DZOs; HR sees only their own DZO.
	ListDZO(ctx context.Context) (*ListDZOResponse, error)

	// GetDZO returns DZO by ID. ADM is scoped to their client.
	GetDZO(ctx context.Context, id string) (*GetDZOResponse, error)

	// UpdateDZO updates DZO. ADM is scoped to their client.
	UpdateDZO(ctx context.Context, id string, p *UpdateDZORequest) (*GetDZOResponse, error)

	// DeleteDZO soft deletes DZO. ADM is scoped to their client.
	DeleteDZO(ctx context.Context, id string) (*DeleteDZOResponse, error)
}
