// Code generated by encore. DO NOT EDIT.

package users

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// GetMe returns the current user, auto-provisioning as EMP on first login.
	GetMe(ctx context.Context) (*GetUserResponse, error)

	// GetUser returns a user by internal ID. SA and ADM only; ADM is scoped to own client.
	GetUser(ctx context.Context, id string) (*GetUserResponse, error)

	// ListUsers returns active users. SA sees all; ADM sees only their client.
	ListUsers(ctx context.Context) (*ListUsersResponse, error)

	// CreateUser creates a user linked to an existing Keycloak identity. SA only.
	CreateUser(ctx context.Context, p *CreateUserRequest) (*GetUserResponse, error)

	// RegisterAdmin creates a new admin in both Keycloak and the database.
	// The SA provides basic user details; the backend provisions the Keycloak account,
	// assigns the ADM realm role, and sets companyId/dzoId JWT attributes automatically.
	// The admin record is created as pending (is_active=false, is_onboarded=false) and
	// is auto-activated when the admin logs in for the first time.
	// SA only.
	RegisterAdmin(ctx context.Context, p *RegisterAdminRequest) (*RegisterAdminResponse, error)

	// AssignRole assigns a role to a user. SA can assign any role; ADM can assign HR only within own DZO.
	AssignRole(ctx context.Context, id string, p *AssignRoleRequest) (*GetUserResponse, error)

	// RemoveRole resets a user's role to EMP.
	RemoveRole(ctx context.Context, id string) (*GetUserResponse, error)

	// BlockUser sets is_active=false. SA and ADM; ADM scoped to own client.
	BlockUser(ctx context.Context, id string) (*MessageResponse, error)

	// UnblockUser sets is_active=true. SA and ADM; ADM scoped to own client.
	UnblockUser(ctx context.Context, id string) (*MessageResponse, error)
}
