// Code generated by encore. DO NOT EDIT.

package suppliers

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	// CreateSupplier creates supplier
	CreateSupplier(ctx context.Context, p *CreateSupplierRequest) (*GetSupplierResponse, error)

	// ListSuppliers returns suppliers with optional filters:
	//   - type: LEGAL | INDIVIDUAL
	//   - is_active: true | false (defaults to true if omitted)
	//   - search: case-insensitive substring match on name
	ListSuppliers(ctx context.Context, p *ListSuppliersParams) (*ListSuppliersResponse, error)

	// ListSuppliersWithBudget returns active suppliers with aggregated budget totals from contracts.
	// Optional filters:
	//   - type: LEGAL | INDIVIDUAL
	//   - is_active: true | false (defaults to true if omitted)
	//   - search: case-insensitive substring match on name
	ListSuppliersWithBudget(ctx context.Context, p *ListSuppliersParams) (*ListSuppliersWithBudgetResponse, error)

	// GetSupplier returns supplier by id.
	GetSupplier(ctx context.Context, id string) (*GetSupplierResponse, error)

	// UpdateSupplier partially updates supplier by id.
	UpdateSupplier(ctx context.Context, id string, p *UpdateSupplierRequest) (*GetSupplierResponse, error)

	// DeleteSupplier soft delete of supplier (is_active = false).
	DeleteSupplier(ctx context.Context, id string) (*DeleteSupplierResponse, error)

	// UploadSuppliers validates uploaded suppliers .xlsx or .csv file before import.
	UploadSuppliers(ctx context.Context, p *UploadSuppliersRequest) (*UploadSuppliersResponse, error)

	// ImportSuppliers imports suppliers from uploaded .xlsx or .csv file.
	ImportSuppliers(ctx context.Context, p *ImportSuppliersRequest) (*ImportSuppliersResponse, error)
}
