// Code generated by encore. DO NOT EDIT.

package categories

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	CreateCategory(ctx context.Context, p *CreateCategoryRequest) (*GetCategoryResponse, error)

	ListCategories(ctx context.Context) (*ListCategoriesResponse, error)

	GetCategory(ctx context.Context, id string) (*GetCategoryResponse, error)

	UpdateCategory(ctx context.Context, id string, p *UpdateCategoryRequest) (*GetCategoryResponse, error)

	DeleteCategory(ctx context.Context, id string) (*DeleteCategoryResponse, error)
}
